### ISSUE TITLE
Q of PDP design

### ISSUE THREAD

**Issue by apolonic** [nvdla/hw#10]
PDP has a dedicated memory interface to fecth input map from memory and output map directly to memory. 
Does this "memory" means the memory outside of DLA? If it does, Is it CPU to reshape the data?
Why not to fetch the input map from the conv buffer? What would be the cost by implementing this design?

**Comment by nvdsmith** [comment]
PDP will get the output from the accumulator directly without needing to first travel through memory.  It's memory interface would be used for other data like bias.  This data could be stored on an on-chip SRAM or in DRAM.
