### ISSUE TITLE
synthesis constraints

### ISSUE THREAD

**Issue by gilbert31932** [nvdla/hw#101]
I cannot set " set_ideal_network [get_pins u_partition_a_reset/synced_rstn] " and corresponding commands to any other partition. I used T40 low power process. It shows that "Warning: Object "link9707" is invalid. It must be a pin of a leaf cell or a port. (OPT-812)
I tried to set the constraint on the pin of a leaf cell of the reset but it didn't work.
How can I solve it? Is it because of the process?
THX!

**Comment by jwise** [comment]
Hmm, ok, I had a look at this.  It looks like we have some changes in the nv_small branch that we're working on that I can port over -- these might help.  Try what I pushed in commit eb2564c and see if that helps some?  I'll close this for now, but if this didn't fix it, please feel free to comment again or re-open the issue.
