### ISSUE TITLE
About VCS Kernel support issue, is this warming will be a problem

### ISSUE THREAD

**Issue by CrazyBingo** [nvdla/hw#106]
Linux: Ubuntu 16.04 LTS 64bit
VCS:  vcs_2015.09_SP2

I have test that vcs can run dependently while compile *.v, but there is a warming like this:

Warning-[LINX_KRNL] Unsupported Linux kernel
  Linux kernel '4.4.0-116-generic' is not supported.
  Supported versions are 2.4* or 2.6*.

I do not know if it is the reason why 'tmake -bult verif_sim' failed with 'CMD-015 error', is there anyone know about this?

TKS

**Comment by jwise** [comment]
You may need a newer version of VCS.  I do not anticipate that this will affect NVDLA, though.  If you continue to have CMD-015 error issues, SolvNet might be the best place for support.
