### ISSUE TITLE
NV_NVDLA_CMAC_CORE_MAC_mul ERROR

### ISSUE THREAD

**Issue by IgnacioGoldman** [nvdla/hw#109]
I would like to know how this module exactly works and which is the difference between INT8 and INT16?
I'm not sure but i think that is not throwing correctly the multiplication result. An example:

op_a_dat = 16h57e5
op_b_dat = 16h4242

res_a = 32h6b6e4dca
res_b = 32h00000040

then... res = res_a+res_b = 32h6b6e4e0a

Can anyone explain me those values? (here i have configured NVDLA at INT8)

**Comment by pumpkinpbk** [comment]
in booth encode the MSB has been inverted, to get the final correct result you have to do the sign compensation, which CMAC is done in the level4 adder tree.

hope this would answer your question.

**Comment by IgnacioGoldman** [comment]
First of all, thanks for answering. Unfortunately still not understanding.

I have moved into INT16 standard testbench conv_8x8 without any modifications and i have the following results

At booth mul level --> multiplication is straightforward
At MUL level --> im not having the expected results. For example:
inputs:     0xAAC3 and 0XE4CE (expected multiplication result 989F 14EA)
outputs:  0x5D18D4EA and 0x014A4000 (the sum is 5E63 14EA)

As you can see they are different and as you say, there's another CSA with the rest of the MUL units...
At MAC level --> given the image and the weight slice, after the multiply and accumulate process i'm expecting..               9 B098 63B1
but i'm having...     3F EC1D 63B1 
value that a proceed until the calculator of partition_a

Are this values ok? if they are ok, which is the relation between the expected value of a simple multiplication?

**Comment by ecqin** [comment]
Any information on this?

**Comment by IgnacioGoldman** [comment]
NVDLA new builds of MAC cell units do not generate BOOTH multipliers explicitly, they are just dot (*) multiplicators. In other words, try to generate the last NVDLA vmod and check how he MAC is described.
(large or small version, is the same)
