### ISSUE TITLE
Unit conflict found about cap unit

### ISSUE THREAD

**Issue by JunningWu** [nvdla/hw#124]
when compile using dc, I got the Error about Constraint cap unit and main library's, which is 1.000000e-04pf VS pF.

I wonder where to set the cap unit, since I doesn't find it in the scripts.

when I set the cap unit in .sdc file, no matter which one used, 1.000000e-04pf or pF, the error remains.

**Comment by nodushiv** [comment]
What is the error message you are seeing in DC?

**Comment by JunningWu** [comment]
@nodushiv from the dc log file, the error message is this

```
ERROR: Unit conflict found: Constraint cap unit is '1.000000e-04pf'; main library cap unit is 'pF'. (IFS-001)
```
like what I have said, when changing the .sdc file, the cap unit in the log file is changed likewise.

**Comment by nodushiv** [comment]
@JunningWu This usually happens when the target_library and link_library are not set correctly, and DC is unable to derive the units from the library. 

Can you ensure that the libraries are being loaded correctly?

If you can attach the whole log file, that would be ideal for debug.

**Comment by nodushiv** [comment]
Closing this issue since I haven't heard back from @JunningWu 
Please reopen and provide more information if this remains to be an issue.
