### ISSUE TITLE
Q of non-maxima suppression

### ISSUE THREAD

**Issue by apolonic** [nvdla/hw#15]
Is this NMS feature supported?

**Comment by pengpeterli** [comment]
NVDLA does not support NMS. Actually, I cannot recall that we have claimed that NVDLA supports NMS.

Based on the questions you have asked, I presume that your application is kind of object detection (probably face/human detection). Would you please share your application information (targeted application field, algorithms, processing pipelines) send email to nvdla@nvidia.com? It will help us to determine which features shall be supported in later versions.
