### ISSUE TITLE
Missing modules during synthesis in CMAC

### ISSUE THREAD

**Issue by Y159753** [nvdla/hw#159]
Design compiler succeed to synthesize 4/5 partitions, however in partition_m there are two modules missing.  

here is the final error message from design compiler : 

Information: Building the design 'DW02_multp' instantiated from design 'NV_NVDLA_CMAC_CORE_mac' with
        the parameters "8,8,18". (HDL-193)
Warning: Cannot find the design 'DW02_multp' in the library 'WORK'. (LBR-1)
Information: Building the design 'DW02_sum' instantiated from design 'NV_NVDLA_CMAC_CORE_mac' with
        the parameters "16,19". (HDL-193)
Warning: Cannot find the design 'DW02_sum' in the library 'WORK'. (LBR-1)
Warning: Unable to resolve reference 'DW02_multp' in 'NV_NVDLA_CMAC_CORE_mac'. (LINK-5)
Warning: Unable to resolve reference 'DW02_sum' in 'NV_NVDLA_CMAC_CORE_mac'. (LINK-5)
Error: Failed to link. Aborting...

**Comment by nvdsmith** [comment]
I suspect you're not licensed for these designware building blocks.  You may need to compile with DW disabled (set USE_DESIGNWARE to 0 in the tree.make file).

**Comment by nodushiv** [comment]
If you are licensed for DesignWare libraries, then you should check the `LINK_LIB` variable in your configuration. Please make sure it includes the DesignWare synthetic library. 

If you have a standard Design Compiler install, these paths can be added to `LINK_LIB`
```
    ${DC_PATH}/../libraries/syn/dw_foundation.sldb
    ${DC_PATH}/../libraries/syn/gtech.db
    ${DC_PATH}/../libraries/syn/standard.sldb
```

**Comment by Y159753** [comment]
My problem is solved, thank you. 
I added the 3 path you gaved in the LINK_LIB. But I also had to include in the TARGET_LIB : 
${DC_PATH}/../libraries/syn/dw_foundation.sldb
${DC_PATH}/../libraries/syn/standard.sldb

**Comment by nodushiv** [comment]
Closing issue.
