### ISSUE TITLE
Does nvdla support object detection

### ISSUE THREAD

**Issue by Adithyak1998** [nvdla/hw#171]
I recently raised an issue in nvdla sw: 
https://github.com/nvdla/sw/issues/67.
I found out that nvdla_compiler doesn't support object detection. 
I just wanted to clarify if the NVDLA HW supports object detection.

**Comment by Adithyak1998** [comment]
Does it support power layer.

I want these to work:
https://raw.githubusercontent.com/NVIDIA/caffe/caffe-0.15/examples/kitti/detectnet_network.prototxt
https://raw.githubusercontent.com/NVIDIA/caffe/caffe-0.15/examples/kitti/detectnet_network-2classes.prototxt

**Comment by nvhook** [comment]
Closing as resolved in nvdla/sw#67 .
