### ISSUE TITLE
NVDLA's Power information?

### ISSUE THREAD

**Issue by rill-zhen** [nvdla/hw#18]
it is well known that "Low Power" is one of the most important feature for embedded deep learning accelerators, what about NVDLA?what's the 'small NVDLA' power (alexnet 1000fps@28nm)?

**Comment by jwise** [comment]
We're working on this and hope to have something in the next few days.

**Comment by jwise** [comment]
We've updated the NVDLA Primer with more information on this: http://nvdla.org/primer.html#example-area-and-performance-with-nvdla

**Comment by rill-zhen** [comment]
thanks so mush, it is a greate help.
