### ISSUE TITLE
How to modify AXI id width of NV_SMALL DDB interface ?

### ISSUE THREAD

**Issue by xivisi** [nvdla/hw#180]
By default, the id width of  ddb is 8, but the slave axi interface of Zynq UltraScale+ MPSoC FPGA is 5 or 6. I do'nt know how many thread in NV_SMALL DMA。

**Comment by mmaciag** [comment]
Please have a look on _NV_NVDLA_NOCIF_DRAM_READ_eg.v_, lines 179-186 in the. Only 4 LSB bits are used. Hope it helps.

**Comment by xivisi** [comment]
That is! Thanks !
