### ISSUE TITLE
master branch (v2) ./tools/bin/tmake -build ready_for_test git respository issue

### ISSUE THREAD

**Issue by owenwu99** [nvdla/hw#182]
It looks that there are some assumptions about the git repository, but my local environment didn't fit in.
First the error message was just as the title showed " fatal: Not a git repository (or any of the parent up to mount point /ddic/na99018). Stopping at filesytem boundary (GIT_DISCOVERY_ACROSS_FILESYSTM not set).
I tried to use the command "git init" in the directory output/nv_small/verif/protection, but the error messages was just changed to "fatal: bad default revision 'HEAD'. Any suggestion for this issue?

**Comment by nvhook** [comment]
This symptom indicates a problem unrelated to nvdla, so you will likely resolve it quicker by searching for the error message in StackExchange (where I found the most responses to this question). In my search I saw no single answer that could be simply pasted here. Depends on your setup. 

When you figure it out, please post the resolution here for others.

**Comment by owenwu99** [comment]
Just as nvhook said, this is not a nvdla issue, but a git issue combined with the assumption everybody uses the git clone approach.
Configuration: using the "Download Zip" not the "Clone" for git clone
Symptom: described as above
Root Cause: in the verif/tools/run_plan.py, there is a "unique_id" value which is expected to be generated by successfully executing the command "git log".
Fix (or better called Fake):  in the directory output/nv_small/verif/protection, executes the following commands to generate a legal .git/HEAD for the command "git log" 
1). git init
2). git add run_protection.py (or any file under this directory)
3). git commit -m "initial_commit"
