### ISSUE TITLE
verif 

### ISSUE THREAD

**Issue by zhibin633** [nvdla/hw#186]
Hi,
i test sanity0 case,the register write and read are OK and expected.But some case that need load mem or dump mem,from the axi interface,i found that the rddata is x state.Like this
SMEM:slave0 read address 0x0080000000,curr_data=0xxxxxxxxxxxxxxx

somebody give me advise?thanks

**Comment by zhibin633** [comment]
It is OK now

**Comment by akrutishivhare** [comment]
Hi,
I am trying to use verilator to run sanity0 and facing similar mem_read issue,could you help with understanding how did you fix it ?

Thanks !

**Comment by zhibin633** [comment]
modify the memory.v,
55 line,reg [`MEM_WIDTH-1:0] memory[0:TOTAL_MEM_SIZE-1]







At 2018-10-02 03:49:44, "akrutishivhare" <notifications@github.com> wrote:


Hi,
I am trying to use verilator to run sanity0 and facing similar mem_read issue,could you help with understanding how did you fix it ?

Thanks !
