### ISSUE TITLE
Regarding testbench simulation

### ISSUE THREAD

**Issue by sethu018** [nvdla/hw#20]
I tried to run sanity test using,
   **make sanity**
   The test hangs. **make build** compiled successfully though. 
   The screenshot of the terminal screen after running make sanity is shown below:
![image](https://user-images.githubusercontent.com/32465661/31094926-7cdf8bce-a77c-11e7-921e-f0c5aa9af93a.png)

**Comment by zdraw** [comment]
Hi, the inp_txn_to_hexdump.pl script is erroring out because we specified #!/home/utils/perl-5/8/8/bin/perl.  Try changing that to point to your perl location. I'll keep this open until we make a nicer error message and change the perl header.

**Comment by sethu018** [comment]
Hi, The sanity test ran after making the suggested changes. Thank you.
