### ISSUE TITLE
NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v Line 748. Undefined system function '$RollPLI'

### ISSUE THREAD

**Issue by zackgd1024** [nvdla/hw#207]
Hi Everyone

I'm trying to implement nv_small on Xilinx ZC104 evaluation board.

During simulation, I've got the following error:
NV_NVDLA_CSB_MASTER_falcon2csb_fifo.v Line 748. Undefined system function '$RollPLI'.

Where can I find function "$RollPLI"?

Any comments would be helpful.

Thanks

**Comment by zackgd1024** [comment]
Since there're no comments. I will close this issue.

**Comment by mmaciag** [comment]
Just define macros that will cut away non-working code. E.g. `SYNTHESIS`. You can also try to follow the changes applied to old nvdlav1 to make XSIM working: https://github.com/nvdla/hw/pull/49
