### ISSUE TITLE
about systemc in NVDLA

### ISSUE THREAD

**Issue by smartchen2k** [nvdla/hw#228]
hi, as the tutorial told in section "tree.make setup", we should use systemc 2.3.0.
And I found the configuration in gived "tree.make" about systmec is:
`Enter systemc path (Press ENTER if use:
/home/ip/shared/inf/SystemC/1.0/20151112/systemc-2.3.0/GCC472_64_DBG):`
what the GCC472_64_DBG is about?

I doult about this is for that when I run a single test, it always returns a error as:

*Verdi3* WARNING: Failed to load SystemC dumper library `libsscore_vcs201606_sc230_gcc48.so'. Disable SystemC dumping support (/home/CAD/synopsys/Verdi3_L-2016.06-1/share/PLI/lib/LINUXAMD64/libsscore_vcs201606_sc230_gcc48.so: undefined symbol: spi_cast_time_pow_0).

and the simulation test failed. So I think maybe there are some mistakes for my systemc, or the relation between synopsys software and the systemc.

Anybody know about that?

**Comment by smartchen2k** [comment]
By the way, verdi works well and the gui can be started.

**Comment by smartchen2k** [comment]
And I noly set $PATH for verdi, any other Environment Variables need to set, such as LD_LIBRARY_PATH?

**Comment by awangsong2012** [comment]
> hi, as the tutorial told in section "tree.make setup", we should use systemc 2.3.0.
> And I found the configuration in gived "tree.make" about systmec is:
> `Enter systemc path (Press ENTER if use: /home/ip/shared/inf/SystemC/1.0/20151112/systemc-2.3.0/GCC472_64_DBG):`
> what the GCC472_64_DBG is about?
> 
> I doult about this is for that when I run a single test, it always returns a error as:
> 
> _Verdi3_ WARNING: Failed to load SystemC dumper library `libsscore_vcs201606_sc230_gcc48.so'. Disable SystemC dumping support (/home/CAD/synopsys/Verdi3_L-2016.06-1/share/PLI/lib/LINUXAMD64/libsscore_vcs201606_sc230_gcc48.so: undefined symbol: spi_cast_time_pow_0).
> 
> and the simulation test failed. So I think maybe there are some mistakes for my systemc, or the relation between synopsys software and the systemc.
> 
> Anybody know about that?

hi，Did you solve that problem? I got the same.  HELP Please!

**Comment by shazib-summar** [comment]
Hey @shgangchen did you find a solution? I am facing the same problem.

**Comment by prasshantg** [comment]
@killerzula you need to update that path to directory where systemc is installed on your system
