### ISSUE TITLE
how can i use second memory slave

### ISSUE THREAD

**Issue by huangleiesc** [nvdla/hw#23]
If I use second memory ,can you supply a simple sram slave controller?
Can I use the “slave_mem_wrap” for synthesis ?

**Comment by zdraw** [comment]
In the current release the tests only exercise the DBB interface. I have unreleased changes that update the slaves inside slave_mem_wrap to use the secondary mem interface path and add tests that demo this. Once it clears our internal process, you can use either the DBB interface or secondary mem interface or both.

It is not recommended that you use testbench code for synthesis. @nodushiv can answer synthesis questions you have.
