### ISSUE TITLE
read_sdc error

### ISSUE THREAD

**Issue by rill-zhen** [nvdla/hw#25]
when i am tring to synthesis the NVDLA at wlm mode,and i got the error info like:
"
Info: Reading input SDC xxx/NV_NVDLA_partition_a.sdc using "read_sdc"
Reading SDC version 2.0
Error: Value for 'object_list' must have 1 elements (CMD-036) 
Error: Value for '-from' must have 1 elements (CMD-036) 
" 
what i should do?

**Comment by rill-zhen** [comment]
#26

**Comment by jwise** [comment]
What version of DC are you using?  (Are you using a non-DC tool for this?)

Thanks,
joshua

**Comment by rill-zhen** [comment]
tank u joshua,i fixed this bug by modifing sdc file,Pls see the pull request.
