### ISSUE TITLE
nv_full.spec: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by piotr-aldec** [nvdla/hw#261]
Hi,

I'm new with nvdla. I'm trying to generate everything and run some simulation. However, I have a problem with ./tools/bin/tmake -build vmod command.
It returns the following error:
**/usr/lib64/ccache/g++ -undef -nostdinc -P -C nv_full.spec -o /space_2/storage/GIT/nvdla/hw/outdir/nv_full/spec/defs/project.def
nv_full.spec: file not recognized: File format not recognized**

I'm using the following configuration:
PROJECTS := nv_full

##======================= 										  
##Linux Environment Setup 										  
##======================= 										  
  																  
## c pre-processor			   									  
CPP  := /usr/lib64/ccache/g++
>>[Piotr@Piotr-Lin hw]$ /usr/lib64/ccache/g++ --version
>>g++ (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
															  
## c++ compiler	      		   									  
GCC  := /usr/lib64/ccache/g++
>>[Piotr@Piotr-Lin hw]$ /usr/lib64/ccache/g++ --version
>>g++ (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)
						  
## perl: many scripts is written in perl 							  
PERL := /usr/bin/perl
>>[Piotr@Piotr-Lin hw]$ /usr/bin/perl --version
>>This is perl 5, version 22, subversion 2 (v5.22.2) built for x86_64-linux-thread-multi
														  
## java: used in hardware regester spec compilation (not in current release)                       
JAVA := /usr/bin/java
>>[Piotr@Piotr-Lin hw]$ /usr/bin/java -version
>>openjdk version "1.8.0_111"
														  
## systemc: needed for Cmodel build (optional)                       
SYSTEMC := /space_0/Storage/Praca/Local_tests/Testy/systemc-2.3.0
  																  
## verilator: used to build testbench without VCS (optional)
VERILATOR := verilator
>>[Piotr@Piotr-Lin hw]$ verilator --version
>>Verilator 3.890 2016-11-25 rev verilator_3_888-18-gc72d473

## clang: used to build Verilated binaries (optional)
CLANG := clang
>>[Piotr@Piotr-Lin hw]$ clang --version
>>clang version 3.7.0 (tags/RELEASE_370/final)

Could you please help with this issue?
I've found a similar issue, but it does not work with g++ and gcc.

Thank you,
Best Regards,
Piotr

**Comment by piotr-aldec** [comment]
Hi,

Sorry, my mistake.

Best Regards,
Piotr

**Comment by jiayi-wang98** [comment]
Could you kindly share how you resolved this issue? I encountered the same issue and don't know the problem here?

Best,
Jiayi
