### ISSUE TITLE
cannot build and install the Virtual simulator

### ISSUE THREAD

**Issue by lznnnnn1998** [nvdla/hw#318]
i have already installed the systemc-2.3.0, but it cannot find the systemc version file....

cmake -DCMAKE_INSTALL_PREFIX=/home/cristinazn/Downloads/vp/VirtualSimulator -DSYSTEMC_PROFIX=/usr/local/systemc-2.3.0/ -DNVDLA_HW_PREFIX=/home/cristinazn/Downloads/vp/hw -DNVDLA_HW_PROJECT=nv_small
-- Searching for SystemC
-- SystemC version = grep: _SYSTEMC_VERSION_FILE-NOTFOUND: No such file or directory.grep: _SYSTEMC_VERSION_FILE-NOTFOUND: No such file or directory.grep: _SYSTEMC_VERSION_FILE-NOTFOUND: No such file or directory
-- SystemC library = SystemC_LIBRARIES-NOTFOUND
CMake Error at CMakeLists.txt:45 (message):
  SystemC library not found.

**Comment by linbaiwpi** [comment]
> i have already installed the systemc-2.3.0, but it cannot find the systemc version file....
> 
> cmake -DCMAKE_INSTALL_PREFIX=/home/cristinazn/Downloads/vp/VirtualSimulator -DSYSTEMC_PROFIX=/usr/local/systemc-2.3.0/ -DNVDLA_HW_PREFIX=/home/cristinazn/Downloads/vp/hw -DNVDLA_HW_PROJECT=nv_small
> -- Searching for SystemC
> -- SystemC version = grep: _SYSTEMC_VERSION_FILE-NOTFOUND: No such file or directory.grep: _SYSTEMC_VERSION_FILE-NOTFOUND: No such file or directory.grep: _SYSTEMC_VERSION_FILE-NOTFOUND: No such file or directory
> -- SystemC library = SystemC_LIBRARIES-NOTFOUND
> CMake Error at CMakeLists.txt:45 (message):
> SystemC library not found.

Hi, I encountered the same issue. Did you solve this and if yes, could you share your solution?
