### ISSUE TITLE
Has considered coding RTL with SystemVerilog?

### ISSUE THREAD

**Issue by rill-zhen** [nvdla/hw#32]
Has considered coding RTL with SystemVerilog which with better readability, higher coding efficiency, supported by allmost all EDA tools.

**Comment by zdraw** [comment]
Nvidia does not typically code design RTL with SystemVerilog, but it is on our roadmap to release a UVM testbench in H1 2018. https://github.com/nvdla/doc/blob/master/doc/roadmap.rst#2018-h1
