### ISSUE TITLE
nv_small tmake building ready_for_test error

### ISSUE THREAD

**Issue by shemadolev** [nvdla/hw#349]
We're trying to build a simple nv_small project. We've passed the stages in [Build Tree](http://nvdla.org/hw/v2/environment_setup_guide.html#build-tree) till `./tools/bin/tmake -build ready_for_test` which generates the following:
![image](https://user-images.githubusercontent.com/57037062/118259195-88ae3600-b4b9-11eb-81a1-3f880ff0dbf1.png)

This is our logfile in `outdir/nv_small/verif/testbench/trace_player/sysc.log`:
[sysc.log](https://github.com/nvdla/hw/files/6478245/sysc.log)
We've noticed 2 things:
1. The include path for SystemC is not as we supplied in the `tree.make`:
![image](https://user-images.githubusercontent.com/57037062/118259919-6832ab80-b4ba-11eb-924e-a285b7358846.png)
2. Seems like it's trying to run a sysc version of 2.3.0, and we can't understand why: The Systemc's version in the path we supplied is 2.3.1 and - when we're trying to change the `SYSC_VER` to 231 in the Makefile in `verif/testbench/trace_player` we're getting this error:
![image](https://user-images.githubusercontent.com/57037062/118261437-37ec0c80-b4bc-11eb-9511-876d266983c6.png)

Any help will be appreciated.

**Comment by LeiWang1999** [comment]
I think you can try this docker container .~

```
docker pull farhanaslam/nvdla 
```

**Comment by shemadolev** [comment]
Solved:
1. We changed the version of systemc in arguments in: `hw/verif/testbench/traceplayer/Makefile`
2. We had a problem with the limit of file descriptors in our machine. Calling `limit descriptors 1024` solved the 'Bad file descriptor' error.

**Comment by ayusdixit** [comment]
> I think you can try this docker container .~
> 
> ```
> docker pull farhanaslam/nvdla 
> ```
is this thing still working? have ran the below command  
`sudo docker run -i -t docker-image-id`
then checked there is nothing 

![Image](https://github.com/user-attachments/assets/56626a45-4d96-4f01-861a-34c7d47a7c3a)
Am i doin correct?
