### ISSUE TITLE
Q:one time one frame

### ISSUE THREAD

**Issue by huangleiesc** [nvdla/hw#38]
in edge device,the ddr is limit and the process latency is sensitive.
if we do batch Calculation
1,the cost of ddr will increase with the number of batch.And in the CNN,the number of datas are also large.and the hidden layer data are more large ,due to the increase of channel.
2,when we collect  16 frames from sensor in the 60fps,the delay is near 300ms. Maybe in some apply,the delay is too long.
so i think ,in the edge device ,the common batch is 1 or 2. in this case ,i see the nvdla's Network MAC Utilization is low.Are you consider to optimization the performance in this case,that batch is low

**Comment by rill-zhen** [comment]
channel extension feature maybe useful.

**Comment by nvdsmith** [comment]
NVDLA doesn't use batching during convolution to fully utilize MAC's.   Is your concern related to fully connected layers?  By their nature, fully connected layers will require higher memory bandwidth for weights, and will benefit from batching.

**Comment by huangleiesc** [comment]
thank you. NVDLA doesn't use batching during convolution to fully utilize MAC's,so there is no problem in my question 1.
