### ISSUE TITLE
g++ link error(GetArgVal)

### ISSUE THREAD

**Issue by rill-zhen** [nvdla/hw#4]
when i run "make" in verif/sim director，it got the error information like:
 5NrIB_d(.data+0x498) undefined reference to GetArgVal.
i tried add '-m64' to g++ cmd line, but it does not work.

**Comment by jwise** [comment]
Hi @rill-zhen , what's your system configuration (version of VCS, etcetera)?

**Comment by jwise** [comment]
@rill-zhen We think we've fixed this.  Please reopen the issue if you continue to have problems.

**Comment by rill-zhen** [comment]
Yes! it worked after i update the project. Thank u very much. @jwise
