### ISSUE TITLE
Syntax/semantic isssue in RANDFUNC hash gen code

### ISSUE THREAD

**Issue by svenka3** [nvdla/hw#5]
Hello,
  First of all great initiative! Thanks!

I am trying to  compile/run this code on Mentor's Questa. I found one small issue (As reported by the tool). 

File:  vmod/vlibs/RANDFUNC.vlib

There is a hash generator function. it uses an assignment like below:

  modName = $sformatf ("%m");

With modName declared as "reg" it doesn't accept - as string to a packed type requires a cast. I did a simple fix as in:

	modName = int'($sformatf ("%m"));

Not sure if that's enough as the modName could be larger than 32 bits maybe? But it maks the compiler happy and it proceeds to running the test (Still fighting other issues in that, so no results yet).

I believe Questa is right in this case and you may be able to run the code with the above change in VCS as well. if not we could add a `ifdef VCS stuff.

Thanks for listening.

Regards
Srini

**Comment by svenka3** [comment]
BTW that change is needed in 2 places inside the same file.

**Comment by jwise** [comment]
Thanks @svenka3.  @zdraw, can you see if this works ok with VCS?

**Comment by zdraw** [comment]
Works in VCS, @svenka3 please reopen if it's still an issue.

**Comment by svenka3** [comment]
This issue seems to be back in a recent build. Kindly fix.

Thanks
Srini

**Comment by jwise** [comment]
Yep, confirmed.  Sorry about that.  I'm taking a look now.

**Comment by jwise** [comment]
I've fixed this in the nvdlav1 branch.
