### ISSUE TITLE
conv_8x8_fc_int16, mem mismatched

### ISSUE THREAD

**Issue by 280185386** [nvdla/hw#53]
checktest : FAILED : .                                        : all transactions completed with no errors but dump_mem mismatched: Found mismatches between ./0.chiplib_dump.raw2 and ./0.chiplib_replay.raw2. 
 
NVINFO : ===============================================================
NVINFO : To summarize the results again, run : make check TESTDIR=../traces/traceplayer/conv_8x8_fc_int16
NVINFO : ===============================================================

**Comment by jwise** [comment]
What version of vcs are you using?  We've seen some issues of this nature with older versions of vcs.

What's in the chiplib_dump/chiplib_replay file?  Is one of them full of 'x'?

**Comment by ShoneAlbert** [comment]
I met this problem also. and there is no chiplib file. I don not know why .  Is this about version if vcs???
it seems can't load memory from the *.dat file

**Comment by jwise** [comment]
I'm closing this, assuming that it's been solved by now, but if not, please feel free to reopen this issue with the requested information.  Thanks!
