### ISSUE TITLE
While we set up verdi environment ourself for NV_nvdla, there is something wrong.

### ISSUE THREAD

**Issue by CrazyBingo** [nvdla/hw#63]
First, We generate the filelist of the files in hw/vmod,  hw/rams, and hw/vlibs,  and designware files(DW_lsd.v DW_minmax.v DW02_tree.v)， Then we set up verdi environment for code review, but sth. is wrong about that:

1. the define syntax shoud not be "#ifdef", but "`ifdef", the same as "`else" "`endif"
![image](https://user-images.githubusercontent.com/20455690/33410511-9701009c-d5bb-11e7-9858-3fcfbef75b4c.png)
2. after replace all about the "#", there is another  error, just look forward
![image](https://user-images.githubusercontent.com/20455690/33410548-cc8d8e24-d5bb-11e7-89fb-90d24c881dea.png)
![image](https://user-images.githubusercontent.com/20455690/33410555-d379d468-d5bb-11e7-8d1e-1caad3ffd14a.png)
3.It seems that the module is redefined. So we modify the first_stage_of_sync in  p_SSYNC3D0.v to first_stage_of_sync 2, and modify the first_stage_of_sync  in p_SSYNC3D0_S_PPP.v to first_stage_of_sync3, then the verdi goes OK.
![image](https://user-images.githubusercontent.com/20455690/33410747-afedea42-d5bc-11e7-809e-cab3a8bdd82c.png)

So the question is, why nvdla script can run right ,while it's error in our own verdi ronvernment.

**Comment by jwise** [comment]
For problem 1, make sure you use the RTL that is in the generated directory after running `tmake`, `outdir/nv_full/vmod`, not in `vmod`.  (See issue #48 / #45, also.)

I'm not sure what the difference is with the SSYNC3D cell; unfortunately, we're not really equipped to diagnose Verdi configurations other than those that we supply with the NVDLA IP.
