### ISSUE TITLE
Semantics issue with reg vs. wire in slave_mem_wrap.v file

### ISSUE THREAD

**Issue by svenka3** [nvdla/hw#7]
File: synth_tb/slave_mem_wrap.v

Lines: 89-112

Current declaration looks like:
  output reg axi_slave0_bready; // Not exact signal name

And then further down the code, this signal is connected to the output of a module instantiation.

Strictly speaking the above should be "output axi_slave0_bready" (i.e. default wire). 

2 tools seem to work OK with original code. XLM (Cadence) throws error. Removing the "reg" makes it go through.

Thanks
Srini

**Comment by jwise** [comment]
Fixed in 5d6de06a.  Thanks!  (Feel free to reopen if needed.)
