### ISSUE TITLE
About dump_mem

### ISSUE THREAD

**Issue by ShoneAlbert** [nvdla/hw#73]
I can compile all the files without any errors. but is hint me can't fine dump_mem file and tells me there is no ...0.chilp.raw2 or something. And I checked it again find if it exists the command load_mem. it will occurred this kind of error. and i want to know the reason. 
Thank you!!!!!!

**Comment by jwise** [comment]
This is not enough information to diagnose the issue; a distillation of error messages is not sufficient, but instead we'll need the exact errors that are produced.  Can you please [create a gist](https://gist.github.com/) with a full log demonstrating the problem?

Thanks!

**Comment by ShoneAlbert** [comment]
And I figure out this problem. The reason is the version of the software. I changed the synopsys software to 2016. And then can run . I find the same prolems before.  And you mentioned it the mem file is all XXXX. anyway thank you
