### ISSUE TITLE
Issue of WGS data  and WMB data?

### ISSUE THREAD

**Issue by lishen565** [nvdla/hw#98]
Hi all , could you tell me the function of wgs data and wmb data in the code? I am puzzled by the relationship between weight data, wgs data and wmb data.  Thanks.

**Comment by fanqifei** [comment]
Hi @lishen565 , you can take a look at http://nvdla.org/hw/format.html#sparse-compression-option

**Comment by lishen565** [comment]
Thank you for your help.@fanqifei

**Comment by lishen565** [comment]
Thank you for your help.@fanqifei

**Comment by lishen565** [comment]
Thank you for your help.@fanqifei

**Comment by lishen565** [comment]
thanks for your help@fanqifei
